version: "3.9"
services:
  elasticsearch:
    image: "elasticsearch:8.4.1"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elasticstack

  kibana:
    image: "kibana:8.4.1"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elasticstack

networks:
  elasticstack:
    driver: bridge
